- hosts: podman_group
  become: true
  tasks:

    - name: Install packages
      ansible.builtin.apt:
        name:
          - podman
        state: present
        update_cache: yes

    - name: Copy podman test script to /home/vagrant/
      copy:
        src: ../podman_test.sh
        dest: /home/vagrant/
        owner: vagrant
        group: vagrant
        mode: '0755'

    # - name: Load msr module
    #   community.general.modprobe:
    #     name: msr
    #     state: present
    
    # - name: Create msr group
    #   ansible.builtin.group:
    #     name: "{{ msr_group }}"
    #     state: present

    # - name: Add vagrant to msr group
    #   ansible.builtin.user:
    #     name: vagrant
    #     groups: msr
    #     append: true
    #     state: present
    #   become: true

    # - name: Ensure vagrant is in msr group
    #   ansible.builtin.command: usermod -aG {{ msr_group }} {{ msr_user }}
    #   become: true
    
    # - name: Set group ownership on /dev/cpu/*/msr
    #   ansible.builtin.shell: chgrp msr /dev/cpu/*/msr
    #   become: true

    # - name: Set group read permission on /dev/cpu/*/msr
    #   ansible.builtin.shell: chmod g+r /dev/cpu/*/msr
    #   become: true
        
    # - name: Unarchive EnergiBridge
    #   ansible.builtin.unarchive:
    #     src: https://github.com/tdurieux/EnergiBridge/releases/download/v0.0.7/energibridge-v0.0.7-x86_64-unknown-linux-musl.tar.gz
    #     dest: /home/vagrant
    #     remote_src: true

    # - name: Set capabilities of EnergiBridge binary
    #   community.general.capabilities:
    #     capability: cap_sys_rawio=ep
    #     path: energibridge
